### ISSUE TITLE
Submit bar resize error when pasting multiple lines of codes

### ISSUE THREAD

**Issue by fugaprascolinas** [qader1/GPT-GUI#1]
Thanks for the work! I have been testing GPT-GUI today, two issues:

1. When I past multiple lines of text in the submit bar, the design breaks and I have to restart GPT-GUI in oder to fix it
2. I can not change font-size for the main screen messages (tried all options in style file, but could not find it)

**Comment by qader1** [comment]
Hi! I made some changes and I will push them soon. I will add also an option in the burger menu to resize the text of message.

1. I disabled rich text input, so only raw text will be taken and colors or formats won't be pasted. Before, the height input bar grows with the text infinitely so I fixed that also and now it only grows to maximum 1/3 of the main window and show a scroll bar.
2. There is a line in the last class in custom_widget.py `self.setFontPointSize(10)`. setting the size in the code seems to override `font-size` in the style file. change the size value from inside the class or remove the line so that it could be changed inside the style. As I mentioned I will add a resize option.

Thank you for the feedback! If the issues persisted, I'd appreciate if you informed me again.

**Comment by qader1** [comment]
Hi, @fugaprascolinas
I pushed updates. Added a menu option to change text or code font sizes and hopefully fixed the bug you experienced. could you test it?

**Comment by fugaprascolinas** [comment]
It is working fine, thanks! Maybe you could add also the option to change the font-size of submit bar (it is hard to read it in small screens)

**Comment by qader1** [comment]
@fugaprascolinas good to hear! I'll implement it in the next couple days. I'll ping you when I push the changes.

**Comment by qader1** [comment]
Hi @fugaprascolinas 
I added an option to change the size of input font. Thanks for the feedback.
